- type: replace
  path: /spring_profiles?
  value: postgresql

- type: replace
  path: /database?
  value:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://((db_host)):((db_port))/((db_name))
    username: ((db_username))
    password: ((db_password))
    maxactive: 4
    maxidle: 3
    minidle: 1
