# Read more at https://github.com/cloudfoundry/uaa/blob/master/docs/google-oidc-provider.md
- type: replace
  path: /login/oauth?/providers/google
  value:
    type: oidc1.0
    authUrl:     https://accounts.google.com/o/oauth2/v2/auth
    tokenUrl:    https://www.googleapis.com/oauth2/v4/token
    tokenKeyUrl: https://www.googleapis.com/oauth2/v3/certs
    issuer:      https://accounts.google.com
    redirectUrl: https://((route))
    scopes:
      - openid
      - email
    linkText: Login with Google
    showLinkText: true
    addShadowUserOnLogin: true
    relyingPartyId:     ((google_client))
    relyingPartySecret: ((google_client_secret))
    skipSslValidation: false
    attributeMappings:
      user_name: email
